### ISSUE TITLE
Title option?

### ISSUE THREAD

**Issue by macsupport** [ytiurin/jsphotocradle#1]
I see in your custom.html you have:

```
{
        thumbnail: '../images/thumbnails/1.jpg',
        preview: '../images/previews/1.jpg',
        original: '../images/originals/1.jpg',
        title: 'Woods troll'
    }
```

Is there an option for the title to show in the carousel or the larger image popup? I'm not seeing where that parameter is utilized.

**Comment by macsupport** [comment]
Still wondering, Is showing the title an option?

**Comment by ytiurin** [comment]
Sorry, not an option(

**Comment by macsupport** [comment]
Hmmm, A question from 2.5 years ago. You must have been busy!  lol  ;-)
